# Generated by Django 5.2.1 on 2025-09-18 04:10

import omochi.common.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Partner store name', max_length=200, null=True)),
                ('image', models.ImageField(help_text='Partner store image (PNG/JPG only)', upload_to='partner_stores/', validators=[omochi.common.utils.validate_image_format])),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers shown first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Store',
                'verbose_name_plural': 'Partner Stores',
                'db_table': 'partner_store',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
