# Generated by Django 5.2 on 2025-04-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP TABLE IF EXISTS qr_scan;
            DROP TABLE IF EXISTS qr_code;
            """,
            reverse_sql="""
            -- This migration removes QR code tables and cannot be reversed automatically
            """
        ),
    ]
