# Generated by Django 5.2 on 2025-05-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_remove_qr_code_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="enable_cash_payment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="qr_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
