# Generated by Django 5.2 on 2025-05-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_venue_additional_info_venue_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="buffer_time",
            field=models.IntegerField(default=15),
        ),
    ]
