# Generated by Django 5.2 on 2025-05-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0004_venue_buffer_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venue",
            old_name="category",
            new_name="genre",
        ),
    ]
