# Generated by Django 5.2 on 2025-05-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_rename_category_venue_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='enable_takeout',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
