# Generated by Django 5.2 on 2025-05-12 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0006_venue_enable_takeout_alter_venue_additional_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venue",
            old_name="enable_takeout",
            new_name="enable_take_out",
        ),
    ]
