# Generated by Django 5.2 on 2025-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0007_rename_enable_takeout_venue_enable_take_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="additional_info",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
