# Generated by Django 5.2 on 2025-05-20 09:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_venue_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSetting',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'venue',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='venue_settings',
                        to='venues.venue',
                    ),
                ),
            ],
            options={
                'db_table': 'venue_setting',
            },
        ),
    ]
