# Generated by Django 5.2 on 2025-05-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0009_venuesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="enable_online_payment",
            field=models.BooleanField(default=False),
        ),
    ]
