# Generated by Django 5.2 on 2025-05-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0010_venue_enable_online_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='nearest_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
