# Generated by Django 5.2 on 2025-05-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0011_venue_nearest_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='venue',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
