# Generated by Django 5.2 on 2025-05-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0012_remove_venue_opening_hours_venue_closing_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockedvenue",
            name="referrer_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
