# Generated by Django 5.2.1 on 2025-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_stockedvenue_referrer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='custom_platform_fee_amount',
            field=models.IntegerField(blank=True, help_text='Absolute application fee amount in JPY for takeout orders', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='payout_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='stripe_account_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Created'), ('VERIFIED', 'Verified'), ('RESTRICTED', 'Restricted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='VenueSetting',
        ),
    ]
