# Generated by Django 5.2.1 on 2025-06-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0014_venue_charges_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockedvenue',
            name='referrer_code',
        ),
    ]
