# Generated by Django 5.2.3 on 2025-07-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_venue_enable_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='announcement',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
