# Generated by Django 5.2.1 on 2025-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_add_announcement_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Address (English)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='announcement_en',
            field=models.TextField(blank=True, null=True, verbose_name='Announcement (English)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_en',
            field=models.CharField(blank=True, null=True, verbose_name='Name (English)'),
        ),
    ]
