# Generated by Django 5.2.1 on 2025-09-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_venue_address_en_venue_announcement_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='additional_info_en',
            field=models.CharField(blank=True, null=True, verbose_name='Additional Info (English)'),
        ),
        migrations.AddField(
            model_name='venue',
            name='genre_en',
            field=models.CharField(blank=True, null=True, verbose_name='Genre (English)'),
        ),
    ]
