# Generated by Django 5.2.1 on 2025-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_add_genre_en_and_additional_info_en_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='nearest_station_en',
            field=models.CharField(blank=True, null=True, verbose_name='Nearest Station (English)'),
        ),
    ]
