# Generated by Django 5.2.1 on 2025-10-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_venue_nearest_station_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_partner',
            field=models.BooleanField(default=True, verbose_name='Is Partner'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
