# Generated by Django 5.2.1 on 2025-10-08 07:21

import omochi.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0021_venue_is_partner_alter_venue_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='announcement',
            field=models.TextField(blank=True, null=True, validators=[omochi.common.utils.validate_announcement_length]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[omochi.common.utils.validate_description_length]),
        ),
    ]
