# Generated by Django 5.2.1 on 2025-10-14 04:52

import django.db.models.deletion
import omochi.venues.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_alter_venue_announcement_alter_venue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='enable_order_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='VenueQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='Question (max 255 characters)', max_length=255, validators=[omochi.venues.models.validate_question_length])),
                ('question_en', models.CharField(blank=True, null=True, verbose_name='Question (English)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the question (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_question',
                'ordering': ['order', 'created_at'],
                'unique_together': {('venue', 'question')},
            },
        ),
    ]
