# Generated by Django 5.2.1 on 2025-10-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0023_venue_enable_order_questions_venuequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venuequestion',
            options={'ordering': ['ordinal', 'created_at']},
        ),
        migrations.RenameField(
            model_name='venuequestion',
            old_name='order',
            new_name='ordinal',
        ),
    ]
