# Generated by Django 5.2.1 on 2025-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0024_alter_venuequestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
