# Generated by Django 5.2.1 on 2025-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='application_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
