# Generated by Django 5.2.1 on 2025-06-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymenttransaction_application_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
