# Generated by Django 5.2 on 2025-05-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='take_out_price',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
