# Generated by Django 5.2 on 2025-05-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0003_menuitem_take_out_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_out_of_stock",
            field=models.BooleanField(
                default=False, help_text="Is this menu item out of stock?"
            ),
        ),
    ]
