# Generated by Django 5.2.1 on 2025-06-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menuitem_is_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_alcoholic',
            field=models.BooleanField(default=False, help_text='Does this menu item contain alcohol?'),
        ),
    ]
