# Generated by Django 5.2.1 on 2025-06-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_menuitem_is_alcoholic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_spicy',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegetarian',
        ),
    ]
