# Generated by Django 5.2.1 on 2025-06-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_remove_menuitem_is_gluten_free_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
