# Generated by Django 5.2.1 on 2025-06-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_menuitem_deleted_at_menuitem_restored_at_and_more'),
        ('venues', '0015_remove_stockedvenue_referrer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_categories', to='venues.venue'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='menus.menucategory'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_items', to='venues.venue'),
        ),
    ]
