# Generated by Django 5.2.1 on 2025-06-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_alter_menucategory_venue_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
