# Generated by Django 5.2.1 on 2025-07-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_alter_menuitem_description'),
        ('venues', '0016_venue_enable_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_priority_pass',
            field=models.BooleanField(default=False, help_text='Is this menu item a priority pass?'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='menu_categories', to='venues.venue'),
        ),
    ]
