# Generated by Django 5.2.1 on 2025-07-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_menuitem_is_priority_pass_alter_menucategory_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='origin_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
