# Generated by Django 5.2.1 on 2025-09-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_menuitem_origin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (English)'),
        ),
    ]
