# Generated by Django 5.2.1 on 2025-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0012_add_multilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='name_en',
            field=models.CharField(blank=True, null=True, verbose_name='Name (English)'),
        ),
    ]
