# Generated by Django 5.2 on 2025-05-16 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
        ('venues', '0007_rename_enable_takeout_venue_enable_take_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='venue',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='coupons',
                to='venues.venue',
            ),
        ),
    ]
