# Generated by Django 5.2 on 2025-05-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_alter_coupon_venue"),
        ("orders", "0006_remove_order_user_coupon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercoupon",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_coupons",
                to="orders.order",
            ),
        ),
    ]
