# Generated by Django 5.2 on 2025-05-21 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_usercoupon_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='value',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='auto_issue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='paid_by',
            field=models.CharField(
                choices=[('OMOCCHI', 'Omochi'), ('VENUE', 'Venue')],
                default='VENUE',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='coupon',
            name='value_type',
            field=models.CharField(
                choices=[
                    ('FIXED_AMOUNT', 'Fixed Amount'),
                    ('PERCENT', 'Percent'),
                    ('FREE_FEE', 'Free Fee'),
                ],
                default='FIXED_AMOUNT',
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='created_user_coupons',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(
                choices=[
                    ('OMOCHI_FEE', 'Omochi Fee'),
                    ('VENUE_FIXED', 'Venue Fixed'),
                    ('CAMPAIGN_FIXED', 'Campaign Fixed'),
                ],
                default='VENUE_FIXED',
                max_length=20,
            ),
        ),
    ]
