# Generated by Django 5.2.1 on 2025-06-05 12:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_rename_value_coupon_amount_coupon_auto_issue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='auto_issue',
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='order_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAKEOUT', 'Takeout'), ('DINE_IN', 'Dine In')], max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='coupon',
            name='payment_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], max_length=15), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('SERVICE_FEE', 'Service Fee'), ('VENUE', 'Issued by Venue'), ('CAMPAIGN', 'Campaign by Omochi')], default='VENUE_FIXED', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value_type',
            field=models.CharField(choices=[('FIXED_AMOUNT', 'Fixed Amount'), ('PERCENT', 'Percent')], default='FIXED_AMOUNT', max_length=15),
        ),
    ]
