# Generated by Django 5.2 on 2025-06-06 04:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_remove_coupon_auto_issue_coupon_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='order_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('TAKEOUT', 'Takeout'), ('DINE_IN', 'Dine In')], max_length=10), blank=True, help_text='Add order types (TAKEOUT, DINE_IN) separate by commas.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='payment_method',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], max_length=15), blank=True, help_text='Add payment methods (CASH, ONLINE) separate by commas.', null=True, size=None),
        ),
    ]
