# Generated by Django 5.2.1 on 2025-06-20 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_usercoupon_discount_amount_alter_coupon_order_type_and_more'),
        ('orders', '0013_alter_orderitem_menu_item_alter_orderitem_order_and_more'),
        ('venues', '0016_venue_enable_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coupons', to='venues.venue'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_coupons', to='coupons.coupon'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_user_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_coupons', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
