# Generated by Django 5.2.1 on 2025-09-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_coupon_deleted_at_coupon_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='usercoupon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('SERVICE_FEE', 'Service Fee'), ('VENUE', 'Issued by Venue'), ('CAMPAIGN', 'Campaign by Omochi')], default='VENUE', max_length=20),
        ),
    ]
