# Generated by Django 5.2.1 on 2025-09-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_alter_coupon_options_alter_usercoupon_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='usercoupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
