# Generated by Django 5.2.1 on 2025-06-05 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0014_venue_charges_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_id', models.CharField(help_text='The ID of the referrer user or referral code', max_length=255)),
                ('action_type', models.CharField(choices=[('REGISTRATION', 'Registration'), ('STOCKED_VENUE', 'Stocked Venue'), ('ORDER', 'Order')], help_text='Type of action that was referred', max_length=20)),
                ('action_id', models.CharField(help_text='ID of the related action (order ID, registration ID, etc.)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, help_text='Additional data related to the reference action', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_logs', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_logs', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Reference Log',
                'verbose_name_plural': 'Reference Logs',
                'db_table': 'ref_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
