# Generated by Django 5.2 on 2025-06-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflog',
            name='action_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('STOCKED_VENUE', 'Stocked Venue'), ('ORDER', 'Order'), ('CLICK', 'Click')], help_text='Type of action that was referred', max_length=20),
        ),
    ]
