# Generated by Django 5.2.1 on 2025-09-15 11:19

import django.db.models.deletion
import omochi.articles.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0017_add_announcement_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True, help_text='Article summary or excerpt', null=True)),
                ('seo_image', models.ImageField(blank=True, help_text='SEO image for social media sharing (PNG/JPG only)', null=True, upload_to='articles/seo/', validators=[omochi.articles.models.validate_image_format])),
                ('content_image', models.ImageField(blank=True, help_text='Main content image (PNG/JPG only)', null=True, upload_to='articles/content/', validators=[omochi.articles.models.validate_image_format])),
                ('content', models.TextField(help_text='Main article content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'article',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleVenueAffiliate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Display title for this venue affiliate', max_length=150)),
                ('social_link', models.URLField(help_text='Social media link for this venue')),
                ('menu_link', models.URLField(blank=True, help_text='Menu link for this venue', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_affiliates', to='articles.article')),
                ('venue', models.ForeignKey(blank=True, help_text='Select a venue (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_affiliates', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Article Venue Affiliate',
                'verbose_name_plural': 'Article Venue Affiliates',
                'db_table': 'article_venue_affiliate',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
