# Generated by Django 5.2 on 2025-05-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_order_code_order_party_size_order_time_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
