# Generated by Django 5.2 on 2025-05-21 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_application_fee_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user_coupon",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user_coupon_value",
        ),
    ]
