# Generated by Django 5.2 on 2025-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_order_user_coupon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
