# Generated by Django 5.2.1 on 2025-05-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_end_time_order_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="end_time",
            field=models.TimeField(default="15:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(default="T2556", max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="start_time",
            field=models.TimeField(default="14:00:00"),
            preserve_default=False,
        ),
    ]
