# Generated by Django 5.2.1 on 2025-05-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_end_time_alter_order_order_code_and_more"),
        ("reservations", "0011_alter_reservation_status_and_more"),
        ("venues", "0013_stockedvenue_referrer_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="reservations.timeslot",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="venues.venue",
            ),
        ),
    ]
