# Generated by Django 5.2.1 on 2025-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_application_fee_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='application_fee_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
