# Generated by Django 5.2.1 on 2025-06-16 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_alter_menucategory_venue_alter_menuitem_category_and_more'),
        ('orders', '0012_order_application_fee_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menus.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_history', to='orders.order'),
        ),
    ]
