# Generated by Django 5.2.3 on 2025-07-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderitem_menu_item_alter_orderitem_order_and_more'),
    ]

    operations = [
        # First, alter the OrderItem model's Meta options
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items - Old'},
        ),
        # Create the OrderItemsMerged model
        migrations.CreateModel(
            name='OrderItemsMerged',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('order_item_id', models.TextField(blank=True, null=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('reservation_id', models.TextField(blank=True, null=True)),
                ('order_code', models.CharField(blank=True, max_length=10, null=True)),
                ('reservation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('venue_id', models.UUIDField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('party_size', models.PositiveIntegerField(blank=True, null=True)),
                ('time_slot_id', models.UUIDField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('application_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('takeout_fee_subsidized_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('menu_item_id', models.UUIDField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('record_type', models.CharField(choices=[('Reservation', 'Reservation'), ('Order', 'Order')], max_length=25)),
            ],
            options={
                'verbose_name': 'Order Item Merge',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items_merge_view',
                'managed': False,
            },
        ),
        # Create the SQL view with unique ID
        migrations.RunSQL(
            sql="""
                DROP VIEW IF EXISTS order_items_merge_view;
                CREATE VIEW order_items_merge_view AS
                SELECT
                    -- Create a unique ID for each row
                    CASE
                        WHEN oi.id IS NOT NULL THEN 'order_item_' || oi.id::text
                        WHEN o.id IS NOT NULL AND r.id IS NOT NULL THEN 'order_' || o.id::text
                        WHEN r.id IS NOT NULL THEN 'reservation_' || r.id::text
                        ELSE 'unknown_' || COALESCE(o.id::text, r.id::text, 'null')
                    END as id,
                    
                    -- Order Item fields
                    oi.id::text as order_item_id,
                    
                    -- Order fields with COALESCE for common fields
                    o.id::text as order_id,
                    o.order_code,
                    COALESCE(o.order_date, r.created_at) as order_date,
                    COALESCE(o.user_id, r.user_id) as user_id,
                    COALESCE(o.venue_id, r.venue_id) as venue_id,
                    COALESCE(o.order_type, 'DINE_IN') as order_type,  -- Default reservations to DINE_IN
                    o.payment_method,
                    COALESCE(o.status, r.status) as status,
                    COALESCE(o.party_size, r.party_size) as party_size,
                    COALESCE(o.time_slot_id, r.time_slot_id) as time_slot_id,
                    COALESCE(o.start_time, r.start_time) as start_time,
                    COALESCE(o.end_time, r.end_time) as end_time,
                    o.total_amount,
                    o.application_fee_amount,
                    o.takeout_fee_subsidized_amount,
                    
                    -- Order Item specific fields
                    oi.menu_item_id,
                    oi.quantity,
                    oi.subtotal,
                    oi.special_request,
                    
                    -- Reservation fields
                    r.id::text as reservation_id,
                    r.reservation_code,
                    
                    -- User details from unified user_id
                    u.email as user_email,
                    
                    -- Venue details from unified venue_id
                    v.name as venue_name,
                    
                    -- Determine record type based on what data is present
                    CASE
                        WHEN r.id IS NOT NULL AND o.id IS NULL THEN 'Reservation'
                        WHEN oi.id IS NOT NULL THEN 'Order'
                        ELSE 'Order'
                    END as record_type
                    
                FROM reservation r
                FULL OUTER JOIN "order" o ON o.reservation_id = r.id
                FULL OUTER JOIN order_item oi ON oi.order_id = o.id
                LEFT JOIN "user" u ON u.id = COALESCE(o.user_id, r.user_id)
                LEFT JOIN venue v ON v.id = COALESCE(o.venue_id, r.venue_id);
            """,
            reverse_sql="DROP VIEW IF EXISTS order_items_merge_view;"
        ),
    ]
