# Generated by Django 5.2.1 on 2025-10-15 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_create_unified_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='Question text at the time of order (Japanese)', max_length=255)),
                ('question_en', models.CharField(blank=True, help_text='Question text at the time of order (English)', max_length=255, null=True)),
                ('answer', models.TextField(help_text="Customer's answer to the question")),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order of the question as it was presented to the customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_questions', to='orders.order')),
            ],
            options={
                'db_table': 'order_question',
                'ordering': ['order_index', 'created_at'],
                'unique_together': {('order', 'order_index')},
            },
        ),
    ]
