# Generated by Django 5.2.1 on 2025-10-23 04:47

import omochi.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_order_question_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderquestion',
            name='answer_en',
            field=models.TextField(blank=True, help_text="Customer's answer to the question (English, max 50 characters)", null=True, validators=[omochi.common.utils.validate_answer_length]),
        ),
        migrations.AlterField(
            model_name='orderquestion',
            name='answer',
            field=models.TextField(help_text="Customer's answer to the question (max 50 characters)", validators=[omochi.common.utils.validate_answer_length]),
        ),
    ]
