# Generated by Django 5.2.1 on 2025-06-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ref_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
