# Generated by Django 5.2.1 on 2025-06-07 07:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_ref_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(help_text='Firebase Cloud Messaging token', unique=True)),
                ('device_type', models.CharField(choices=[('WEB', 'Web Browser'), ('ANDROID', 'Android'), ('IOS', 'iOS')], default='WEB', max_length=10)),
                ('device_id', models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active and valid')),
                ('last_used', models.DateTimeField(auto_now=True, help_text='Last time this token was used for notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_token',
                'indexes': [models.Index(fields=['user', 'is_active'], name='fcm_token_user_id_25e98b_idx'), models.Index(fields=['token'], name='fcm_token_token_38983f_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
