# Generated by Django 5.2.1 on 2025-06-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fcmtoken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together=set(),
        ),
    ]
