# Generated by Django 5.2.1 on 2025-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_fcmtoken_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('ja', 'Japanese'), ('en', 'English')], default='ja', max_length=10),
        ),
    ]
