# Generated by Django 5.2.1 on 2025-11-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='ip',
            field=models.CharField(blank=True, help_text='Requester IP for rate limiting', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['ip', 'created_at'], name='password_re_ip_c32a03_idx'),
        ),
    ]
