# Generated by Django 5.2.1 on 2025-06-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='click_action',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
