# Generated by Django 5.2.1 on 2025-06-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_click_action_notification_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ORDER_STATUS', 'Order Status'), ('RESERVATION', 'Reservation'), ('SYSTEM', 'System'), ('TIME_SLOT_AVAILABLE', 'Time Slot Available')], max_length=20),
        ),
    ]
