# Generated by Django 5.2.1 on 2025-12-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_message_en_notification_title_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Notification', 'verbose_name_plural': 'Admin Notifications'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='message_en',
            field=models.TextField(blank=True, null=True, verbose_name='Message (English)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title_en',
            field=models.CharField(blank=True, null=True, verbose_name='Title (English)'),
        ),
    ]
