# Generated by Django 5.2.1 on 2025-12-09 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotificationReadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Notification Read Status',
                'verbose_name_plural': 'System Notification Read Statuses',
                'db_table': 'system_notification_read_status',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='is_broadcast',
            field=models.BooleanField(default=False, help_text='True if this is a broadcast notification sent via Firebase Topic to all users. Broadcast notifications have user=NULL and are shown to all non-venuer users dynamically.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', help_text='Read status. For broadcast notifications, this is default value (actual status tracked per-user via SystemNotificationReadStatus)', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who receives this notification. NULL for broadcast notifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_26141b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_broadcast', 'created_at'], name='notificatio_is_broa_56e8c6_idx'),
        ),
        migrations.AddField(
            model_name='systemnotificationreadstatus',
            name='notification',
            field=models.ForeignKey(help_text='The broadcast notification this read status belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='systemnotificationreadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notification_read_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemnotificationreadstatus',
            index=models.Index(fields=['user', 'notification'], name='system_noti_user_id_4ffa78_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotificationreadstatus',
            index=models.Index(fields=['notification', 'is_read'], name='system_noti_notific_f28a47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemnotificationreadstatus',
            unique_together={('user', 'notification')},
        ),
    ]
