# Generated by Django 5.2.1 on 2025-06-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(max_length=64)),
                ('station', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'area',
                'ordering': ['prefecture', 'station'],
                'unique_together': {('prefecture', 'station')},
            },
        ),
    ]
