# Generated by Django 5.2.1 on 2025-09-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='prefecture_en',
            field=models.CharField(blank=True, default='', verbose_name='Prefecture (English)'),
        ),
        migrations.AddField(
            model_name='area',
            name='station_en',
            field=models.CharField(blank=True, default='', verbose_name='Station (English)'),
        ),
    ]
