"""
Django settings for omochi project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables from .env file
load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-h5yndne%7q&ttu==h6$yp=ex28%e3ro)0u)(&4cq8b88iz%hz^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']  # Updated for serverless deployment

# Configure logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            'format': '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "name": "%(name)s", "file": "%(filename)s", "line": "%(lineno)d", "function": "%(funcName)s", "message": "%(message)s"}',
            'datefmt': '%Y-%m-%dT%H:%M:%S%z',
            'class': 'pythonjsonlogger.jsonlogger.JsonFormatter',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'omochi': {  # Add a custom logger for your application
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # Added for sitemap support
    'django_extensions',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',  # Required for token blacklisting
    'drf_spectacular',
    'corsheaders',  # Added for CORS support
    # Add for S3 storage
    'storages',
    # Custom apps
    'omochi.common',
    'omochi.users',
    'omochi.venues',
    'omochi.menus',
    'omochi.orders',
    'omochi.reservations',
    'omochi.notifications',
    'omochi.carts',
    'omochi.payments',
    'omochi.coupons',
    'omochi.campaigns',
    'omochi.articles',
    'omochi.partner_stores',
    'omochi.system_setting',
    'omochi.ref_logs',
    'omochi.areas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Add locale middleware for language detection
    'corsheaders.middleware.CorsMiddleware',  # Added for CORS support - must be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'omochi.middlewares.GlobalErrorHandlerMiddleware',  # Global error handler middleware
]

# CORS Configuration
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173').split(',')
CORS_ALLOW_CREDENTIALS = os.environ.get('CORS_ALLOW_CREDENTIALS', 'True') == 'True'
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

ROOT_URLCONF = 'omochi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'omochi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'omochi_db'),
        'USER': os.environ.get('DB_USER', 'omochi_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'omochi_password'),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Available languages for the application
from django.utils.translation import gettext_lazy as _
LANGUAGES = [
    ('en', _('English')),
    ('ja', _('Japanese')),
]

# Location where Django looks for translation files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'omochi/locale'),
]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True  # Format dates, numbers, etc. according to locale
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default local static files configuration
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# AWS S3 configuration for static and media files
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'

if USE_S3:
    # AWS Settings for boto3 and django-storages
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'omochi-static-dev')
    AWS_DEFAULT_ACL = 'public-read'
    
    # Important for LocalStack - Force proper endpoint URL
    # Only set endpoint URL if explicitly provided in environment, otherwise use default AWS endpoints
    endpoint_url = os.environ.get('AWS_S3_ENDPOINT_URL')
    if endpoint_url and endpoint_url.strip():
        AWS_S3_ENDPOINT_URL = endpoint_url
        AWS_S3_REGION_NAME = None  # Not needed for LocalStack
        AWS_S3_ADDRESSING_STYLE = 'path'  # path-style URLs work better with LocalStack
    else:
        # For standard AWS S3, don't set an endpoint URL
        # but do set the region
        AWS_S3_REGION_NAME = os.environ.get('AWS_REGION', 'ap-northeast-1')
    
    # Fix for Django Storage URLs
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_CUSTOM_DOMAIN = None  # Let django-storages build the correct URLs
    
    # Explicitly define locations for static and media
    STATIC_LOCATION = 'static'
    MEDIA_LOCATION = 'media'
    
    # Configure storage backends explicitly
    STORAGES = {
        "default": {
            "BACKEND" : "storages.backends.s3boto3.S3StaticStorage",
        },
        "staticfiles":  {
            "BACKEND" : "storages.backends.s3boto3.S3StaticStorage",
        },
    }

    STATICFILES_STORAGE = 'omochi.storage_backends.StaticStorage'
    DEFAULT_FILE_STORAGE = 'omochi.storage_backends.MediaStorage'
    
    # Build URLs correctly based on environment
    if endpoint_url and ('localhost' in endpoint_url or '127.0.0.1' in endpoint_url):
        # LocalStack environment
        STATIC_URL = f"{endpoint_url}/{AWS_STORAGE_BUCKET_NAME}/{STATIC_LOCATION}/"
        MEDIA_URL = f"{endpoint_url}/{AWS_STORAGE_BUCKET_NAME}/{MEDIA_LOCATION}/"
    else:
        # Real AWS environment - use region-specific URL
        region = AWS_S3_REGION_NAME or 'us-east-1'
        STATIC_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{region}.amazonaws.com/{STATIC_LOCATION}/"
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{region}.amazonaws.com/{MEDIA_LOCATION}/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# User substitution
AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# Password reset token lifetime (in minutes)
PASSWORD_RESET_TOKEN_LIFETIME = int(os.environ.get('PASSWORD_RESET_TOKEN_LIFETIME', '10'))  # minutes

SPECTACULAR_SETTINGS = {
    'TITLE': 'Omochi API',
    'DESCRIPTION': 'RESTful API for the Omochi System - A restaurant management and ordering platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'CONTACT': {
        'name': 'Omochi Support',
        'email': 'support@omochi.app',
    },
    'LICENSE': {
        'name': 'Proprietary',
    },
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'defaultModelsExpandDepth': 3,
        'defaultModelExpandDepth': 3,
    },
}

# Stripe Payment Settings
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_CONNECT_WEBHOOK_SECRET = os.environ.get('STRIPE_CONNECT_WEBHOOK_SECRET', '')
STRIPE_API_VERSION = os.environ.get('STRIPE_API_VERSION', '2025-04-30.basil')
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# Firebase Cloud Messaging Settings (V1 API)
FIREBASE_CREDENTIALS_PATH = os.environ.get('FIREBASE_CREDENTIALS_PATH', '')
FIREBASE_CREDENTIALS_JSON = os.environ.get('FIREBASE_CREDENTIALS_JSON', '')
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '')
# Firebase Topics for broadcasting to all users (excluding venuers) by language
FIREBASE_TOPIC_JA = 'all-users-ja'  # Japanese users topic
FIREBASE_TOPIC_EN = 'all-users-en'  # English users topic

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@omochi.app')

# BCC Email for invoice notifications
INVOICE_BCC_EMAIL = os.environ.get('INVOICE_BCC_EMAIL', 'info@omochiapp.com')

# AWS Configuration
AWS_DEFAULT_REGION = os.environ.get('AWS_DEFAULT_REGION', 'ap-northeast-1')

# Celery Configuration
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False') == 'True'

# OpenAI Configuration
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o-mini')
OPENAI_TEMPERATURE = float(os.environ.get('OPENAI_TEMPERATURE', '1'))  # Lower temperature for more consistent translations
OPENAI_MAX_TOKENS = int(os.environ.get('OPENAI_MAX_TOKENS', '5000'))  # Maximum tokens for responses