# Generated by Django 5.2.3 on 2025-09-03 09:20

import django.db.models.deletion
import omochi.campaigns.models
import omochi.common.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0017_add_announcement_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('venue_notice', 'Venue Notice'), ('global', 'Global')], default='venue_notice', max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cta_link', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('target_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaigns/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Image',
                'verbose_name_plural': 'Campaign Images',
                'db_table': 'campaign_image',
                'ordering': ['order', 'created_at'],
            },
            bases=(omochi.common.utils.UniqueFileUploadMixin, models.Model),
        ),
    ]
