# Generated by Django 5.2.1 on 2025-11-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
    ]
