# Generated by Django 5.2 on 2025-05-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_rename_time_slot_reservation_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="time_slot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.timeslot",
            ),
            preserve_default=False,
        ),
    ]
