# Generated by Django 5.2 on 2025-05-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_reservation_time_slot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="day_of_week",
        ),
    ]
