# Generated by Django 5.2 on 2025-05-14 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_timeslot_day_of_week'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationStatusHistory',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'old_status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('CONFIRMED', 'Confirmed'),
                            ('COMPLETED', 'Completed'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    'new_status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('CONFIRMED', 'Confirmed'),
                            ('COMPLETED', 'Completed'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        max_length=10,
                    ),
                ),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                (
                    'changed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reservation_status_changes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'reservation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='status_history',
                        to='reservations.reservation',
                    ),
                ),
            ],
            options={
                'db_table': 'reservation_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
