# Generated by Django 5.2 on 2025-05-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_reservationstatushistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservation_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
