# Generated by Django 5.2 on 2025-05-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_reservation_reservation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="is_paused",
            field=models.BooleanField(
                default=False, help_text="Time frame pause status"
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="temporary_additional_limit",
            field=models.IntegerField(default=0, help_text="Temporary limit added"),
        ),
    ]
