# Generated by Django 5.2 on 2025-05-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_timeslot_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='service_type',
            field=models.CharField(
                choices=[('EAT_IN', 'Eat-in'), ('TAKE_OUT', 'Take-out')],
                default='EAT_IN',
                max_length=25,
            ),
        ),
    ]
