# Generated by Django 5.2 on 2025-05-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_timeslot_service_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="service_type",
            field=models.CharField(
                choices=[("TAKEOUT", "Takeout"), ("DINE_IN", "Dine In")],
                default="DINE_IN",
                max_length=25,
            ),
        ),
    ]
