# Generated by Django 5.2 on 2025-05-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_timeslot_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='temporary_additional_limit',
        ),
        migrations.CreateModel(
            name='TimeSlotDailyLimit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('date', models.DateField(auto_now_add=True)),
                ('temporary_additional_limit', models.IntegerField(default=0)),
                (
                    'time_slot',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='daily_limits',
                        to='reservations.timeslot',
                    ),
                ),
            ],
            options={
                'db_table': 'time_slot_daily_limit',
                'unique_together': {('time_slot', 'date')},
            },
        ),
    ]
