# Generated by Django 5.2.1 on 2025-07-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_timeslot_deleted_at_timeslot_restored_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='priority_pass_slot',
            field=models.IntegerField(default=0, help_text='Number of priority pass slots'),
        ),
    ]
